import { TABLE_DEPTH, TABLE_LANE, TABLE_SIDE, getZoneId } from './tableZones'

const A = TABLE_SIDE.OWN
const B = TABLE_SIDE.OPPONENT

export const TRAINING_ZONES = {
  A_SHORT_BH: getZoneId(A, TABLE_DEPTH.SHORT, TABLE_LANE.LEFT),
  A_SHORT_MID: getZoneId(A, TABLE_DEPTH.SHORT, TABLE_LANE.MIDDLE),
  A_SHORT_FH: getZoneId(A, TABLE_DEPTH.SHORT, TABLE_LANE.RIGHT),
  A_LONG_BH: getZoneId(A, TABLE_DEPTH.LONG, TABLE_LANE.LEFT),
  A_LONG_MID: getZoneId(A, TABLE_DEPTH.LONG, TABLE_LANE.MIDDLE),
  A_LONG_FH: getZoneId(A, TABLE_DEPTH.LONG, TABLE_LANE.RIGHT),
  B_SHORT_BH: getZoneId(B, TABLE_DEPTH.SHORT, TABLE_LANE.RIGHT),
  B_SHORT_MID: getZoneId(B, TABLE_DEPTH.SHORT, TABLE_LANE.MIDDLE),
  B_SHORT_FH: getZoneId(B, TABLE_DEPTH.SHORT, TABLE_LANE.LEFT),
  B_LONG_BH: getZoneId(B, TABLE_DEPTH.LONG, TABLE_LANE.RIGHT),
  B_LONG_MID: getZoneId(B, TABLE_DEPTH.LONG, TABLE_LANE.MIDDLE),
  B_LONG_FH: getZoneId(B, TABLE_DEPTH.LONG, TABLE_LANE.LEFT),
}

export function getDrillZoneIds(steps = []) {
  return steps.map((step) => step.zoneId).filter(Boolean)
}
